library(shiny)
shinyUI(navbarPage("Retail Demo", id = "m2m", inverse = TRUE, collapsable = FALSE,
 
  tabPanel("Country View",
	sidebarPanel(radioButtons("selection", "SELECT ONE OPTION",
								c("Sales Value" = "sales","Sales By Brand Volume" = "brand")),
				selectInput("brand_selection","SELECT ONE BRANDS",c("BRAND1"="BRAND1",
																	"BRAND2"="BRAND2"),selected="BRAND1",multiple=TRUE),
		h6("*By default it shows BRAND1")),
		htmlOutput("page1"),
		tags$head(
							tags$style(type="text/css", "select { width: 200px; }"),
							tags$style(type="text/css", "textarea { max-width: 85px; }"),
							tags$style(type="text/css", ".jslider { max-width: 200px; }"),
							tags$style(type='text/css', ".well { max-width: 230px; }"),
							tags$style(type='text/css', ".span4 { max-width: 230px; }"))
		),

  tabPanel("State View",    
	sidebarPanel(selectInput("state_selection","SELECT ONE STATE",c("Jammu and Kashmir"="Jammu and Kashmir",
																	"Himachal Pradesh"="Himachal Pradesh",
																	"Punjab"="Punjab",
																	"Uttaranchal"="Uttaranchal",
																	"Haryana"="Haryana",
																	"Delhi"="Delhi",
																	"Rajasthan"="Rajasthan",
																	"Uttar Pradesh"="Uttar Pradesh",
																	"Bihar"="Bihar",
																	"Sikkim"="Sikkim",
																	"Arunachal Pradesh"="Arunachal Pradesh",
																	"Nagaland"="Nagaland",
																	"Manipur"="Manipur",
																	"Mizoram"="Mizoram",
																	"Tripura"="Tripura",
																	"Meghalaya"="Meghalaya",
																	"Assam"="Assam",
																	"West Bengal"="West Bengal",
																	"Jharkhand"="Jharkhand",
																	"Orissa"="Orissa",
																	"Chhattisgarh"="Chhattisgarh",
																	"Madhya Pradesh"="Madhya Pradesh",
																	"Gujarat"="Gujarat",
																	"Maharashtra"="Maharashtra",
																	"Andhra Pradesh"="Andhra Pradesh",
																	"Karnataka"="Karnataka",
																	"Kerala"="Kerala",
																	"Tamil Nadu"="Tamil Nadu"),selected="Karnataka",multiple=FALSE),
				radioButtons("selection", "SELECT ONE OPTION",
								c("Sales Value" = "sales","Sales By Brand Volume" = "brand")),
				selectInput("brand_selection","SELECT ONE BRANDS",c("BRAND1"="BRAND1",
																	"BRAND2"="BRAND2"),selected="BRAND1",multiple=TRUE),
				h6("*By default it shows BRAND1 and Karnataka State only")),
				htmlOutput("page2")
  ),
  tabPanel("Distributor View",    
	sidebarPanel(selectInput("Distributor_selection","SELECT ONE DISTRIBUTOR",c("ASHWINI DISTRIBUTORS"="ASHWINI DISTRIBUTORS",
																				"CHANDANA ENTERPRISES"="CHANDANA ENTERPRISES",
																				"CHANDRAKALA DISTRIBUTORS"="CHANDRAKALA DISTRIBUTORS",
																				"DARSHAN ENTERPRISES"="DARSHAN ENTERPRISES",
																				"DINESH AGENSIES"="DINESH AGENSIES",
																				"JAYASHREE AGENSIES"="JAYASHREE AGENSIES",
																				"KAVITA AGENSIES"="KAVITA AGENSIES",
																				"MANASA AGENSIES"="MANASA AGENSIES",
																				"MOHAMMED AGENSIES"="MOHAMMED AGENSIES",
																				"MOHAN DISTRIBUTORS"="MOHAN DISTRIBUTORS",
																				"MONIKA DISTRIBUTORS"="MONIKA DISTRIBUTORS",
																				"NAGARAJA DISTRIBUTORS"="NAGARAJA DISTRIBUTORS",
																				"NIRMALA ENTERPRISES"="NIRMALA ENTERPRISES",
																				"PAVITHRA AGENSIES"="PAVITHRA AGENSIES",
																				"POORNIMA AGENSIES"="POORNIMA AGENSIES",
																				"PRATHAP DISTRIBUTORS"="PRATHAP DISTRIBUTORS",
																				"PRIYA ENTERPRISES"="PRIYA ENTERPRISES",
																				"RADHIKA ENTERPRISES"="RADHIKA ENTERPRISES",
																				"RASHMI ENTERPRISES"="RASHMI ENTERPRISES",
																				"RAVI ENTERPRISES"="RAVI ENTERPRISES",
																				"ROHINI ENTERPRISES"="ROHINI ENTERPRISES",
																				"SANTOSH DISTRIBUTORS"="SANTOSH DISTRIBUTORS",
																				"SHARATH DISTRIBUTORS"="SHARATH DISTRIBUTORS",
																				"SHIVAKUMAR AGENSIES"="SHIVAKUMAR AGENSIES",
																				"SRIKANTH AGENSIES"="SRIKANTH AGENSIES",
																				"SUSHMA AGENSIES"="SUSHMA AGENSIES",
																				"SUSHMITHA DISTRIBUTORS"="SUSHMITHA DISTRIBUTORS",
																				"TABASSUM AGENSIES"="TABASSUM AGENSIES"),selected="ASHWINI DISTRIBUTORS",multiple=FALSE),
				radioButtons("selection", "SELECT ONE OPTION",
							c("Sales Value" = "sales","Sales By Brand Volume" = "brand")),
				selectInput("brand_selection","SELECT ONE BRANDS",c("BRAND1"="BRAND1",
																	"BRAND2"="BRAND2"),selected="BRAND1",multiple=TRUE),
				h6("*By default it shows BRAND1 and ASHWINI DISTRIBUTORS only")),
				htmlOutput("page3")
	),

  tabPanel("Target",htmlOutput("page4")),
  tabPanel("About",htmlOutput("about.html"))
))